name: pims
channels:
- defaults
- conda-forge
dependencies:
- numpy
- slicerator
- pillow
- matplotlib
- scikit-image
- jinja2
- av
- tifffile
- jpype1
- ipython
- sphinx
- sphinx_rtd_theme
- numpydoc
- moviepy
- imageio
- imageio-ffmpeg
- openjdk
